sonar.projectKey=rgkim-hsu_Smart-Agriculture
sonar.organization=rgkim-hsu
sonar.projectName=Smart Agriculture ThingsBoard
sonar.projectVersion=1.0

# Python 스크립트 위치
sonar.sources=.

# tests 폴더 없으므로 주석 처리 또는 삭제
# sonar.tests=tests

# Python 커버리지
sonar.python.coverage.reportPaths=coverage.xml

# 제외
sonar.exclusions=**/__pycache__/**,**/venv/**,**/.env,**/data/**,**/*.txt,**/*.md,**/*.docx,**/*.pptx,**/*.mp4

# Python 버전
sonar.python.version=3.7,3.8,3.9,3.10
